name: distinctly_redux
version: 1.0.0
description: A Redux store with only distinct onChange notifications.
homepage: https://github.com/johncblandii/distinctly_redux.dart
authors:
  - John C. Bland II <johncblandii@gmail.com>
  - Jeroen Cranendonk <jeroen.cranendonk@gmail.com>

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  redux: ^2.0.0

dev_dependencies:
  build: any
  build_runner: any
  built_value: ^4.0.0
  built_value_generator: any
  coverage: ^0.8.0
  dart_dev: 2.0.0-alpha
  dart_style: ^0.2.0
  dartdoc: ^0.9.0
  test: ^0.12.0
  source_gen: any
